name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.3'

    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.5.1

    - name: Install dependencies
      run: poetry install

    - name: Run make all inside Poetry shell
      run: poetry run make

    - uses: ncipollo/release-action@v1
      if: ${{ !env.ACT }} # Skips step on act-cli during testing
      with:
        artifacts: "release/*"
        tag: ${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: dev-drprasad/delete-older-releases@v0.1.0
      if: ${{ !env.ACT }} # Skips step on act-cli during testing
      with:
        keep_latest: 3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
